# ────────────────────────────────────────────────────────────────────────────
# AVIN
# Understand the market before trading it.
#
# https://avin.info
# ────────────────────────────────────────────────────────────────────────────
# CREATED: 2023.07.23 15:06

[workspace]
resolver = "3"
members = [
    "crates/avin",
    "crates/avin_model",
    "crates/avin_utils",
    "py_bind",
]

[workspace.package]
edition = "2024"
version = "0.1.0"

[workspace.dependencies]
avin = { path = "crates/avin" }
avin_model = { path = "crates/avin_model" }
avin_utils = { path = "crates/avin_utils" }
py_bind = { path = "py_bind" }

pyo3 = "0.29"
