[workspace]
resolver = "3"
members = [
    "crates/*",
    "binds",
]

[workspace.package]
description = "Open source cross-platform trading system"
version = "0.4.0"
edition = "2024"
license = "MIT"
readme = "README.md"
authors = ["Alex Avin <mr.alexavin@gmail.com>"]
repository = "https://github.com/arsvincere/avin"
homepage = "https://avin.info"
categories = ["finance"]
keywords = [
    "trading",
    "algorithmic-trading",
    "trading-platform",
    "backtesting",
    "market-data",
]

[workspace.dependencies]
avin = { path = "crates/avin" }
avin_core = { path = "crates/avin_core" }
avin_domain = { path = "crates/avin_domain" }
avin_utils = { path = "crates/avin_utils" }

log = { version = "0.4", features = ["std"] }
chrono = "0.4"
pyo3 = { version = "0.29", features = ["chrono"] }
serde = { version = "1", features = ["derive"] }
tempfile = "3"
toml = "1"
zip = "8"

polars = { version = "0.55", features = ["parquet"] }
