[workspace]
resolver = "3"
members = [
    "crates/avin",
    "crates/avin_model",
    "crates/avin_utils",
    "py_bind",
]

[workspace.package]
edition = "2024"
version = "0.1.0"

[workspace.dependencies]
avin_model = { path = "crates/avin_model" }
avin_utils = { path = "crates/avin_utils" }

pyo3 = "0.29"
