/*****************************************************************************
 * URL:         http://avin.info
 * AUTHOR:      Alex Avin
 * E-MAIL:      mr.alexavin@gmail.com
 * LICENSE:     MIT
 ****************************************************************************/

use chrono::{DateTime, Local, NaiveDateTime, Utc};
use polars::prelude::{DataFrame, DataType, Field, Schema, df};

#[derive(Debug, Clone, Copy)]
pub struct Bid {
    pub price: f64,
    pub lots: i64,
    pub value: f64,
}
impl Bid {
    pub fn new(price: f64, lots: i64, value: f64) -> Self {
        Bid { price, lots, value }
    }
}

#[derive(Debug, Clone, Copy)]
pub struct Ask {
    pub price: f64,
    pub lots: i64,
    pub value: f64,
}
impl Ask {
    pub fn new(price: f64, lots: i64, value: f64) -> Self {
        Ask { price, lots, value }
    }
}

#[derive(Debug, Clone)]
pub struct OrderBook {
    pub ts: i64,
    pub bids: Vec<Bid>,
    pub asks: Vec<Ask>,
}
impl OrderBook {
    pub fn new(ts: i64, bids: Vec<Bid>, asks: Vec<Ask>) -> Self {
        OrderBook { ts, bids, asks }
    }
    pub fn schema() -> Schema {
        Schema::from_iter(vec![
            Field::new("ts_nanos".into(), DataType::Int64),
            Field::new("bid_0_price".into(), DataType::Float64),
            Field::new("bid_1_price".into(), DataType::Float64),
            Field::new("bid_2_price".into(), DataType::Float64),
            Field::new("bid_3_price".into(), DataType::Float64),
            Field::new("bid_4_price".into(), DataType::Float64),
            Field::new("bid_5_price".into(), DataType::Float64),
            Field::new("bid_6_price".into(), DataType::Float64),
            Field::new("bid_7_price".into(), DataType::Float64),
            Field::new("bid_8_price".into(), DataType::Float64),
            Field::new("bid_9_price".into(), DataType::Float64),
            Field::new("bid_10_price".into(), DataType::Float64),
            Field::new("bid_11_price".into(), DataType::Float64),
            Field::new("bid_12_price".into(), DataType::Float64),
            Field::new("bid_13_price".into(), DataType::Float64),
            Field::new("bid_14_price".into(), DataType::Float64),
            Field::new("bid_15_price".into(), DataType::Float64),
            Field::new("bid_16_price".into(), DataType::Float64),
            Field::new("bid_17_price".into(), DataType::Float64),
            Field::new("bid_18_price".into(), DataType::Float64),
            Field::new("bid_19_price".into(), DataType::Float64),
            Field::new("bid_20_price".into(), DataType::Float64),
            Field::new("bid_21_price".into(), DataType::Float64),
            Field::new("bid_22_price".into(), DataType::Float64),
            Field::new("bid_23_price".into(), DataType::Float64),
            Field::new("bid_24_price".into(), DataType::Float64),
            Field::new("bid_25_price".into(), DataType::Float64),
            Field::new("bid_26_price".into(), DataType::Float64),
            Field::new("bid_27_price".into(), DataType::Float64),
            Field::new("bid_28_price".into(), DataType::Float64),
            Field::new("bid_29_price".into(), DataType::Float64),
            Field::new("bid_30_price".into(), DataType::Float64),
            Field::new("bid_31_price".into(), DataType::Float64),
            Field::new("bid_32_price".into(), DataType::Float64),
            Field::new("bid_33_price".into(), DataType::Float64),
            Field::new("bid_34_price".into(), DataType::Float64),
            Field::new("bid_35_price".into(), DataType::Float64),
            Field::new("bid_36_price".into(), DataType::Float64),
            Field::new("bid_37_price".into(), DataType::Float64),
            Field::new("bid_38_price".into(), DataType::Float64),
            Field::new("bid_39_price".into(), DataType::Float64),
            Field::new("bid_40_price".into(), DataType::Float64),
            Field::new("bid_41_price".into(), DataType::Float64),
            Field::new("bid_42_price".into(), DataType::Float64),
            Field::new("bid_43_price".into(), DataType::Float64),
            Field::new("bid_44_price".into(), DataType::Float64),
            Field::new("bid_45_price".into(), DataType::Float64),
            Field::new("bid_46_price".into(), DataType::Float64),
            Field::new("bid_47_price".into(), DataType::Float64),
            Field::new("bid_48_price".into(), DataType::Float64),
            Field::new("bid_49_price".into(), DataType::Float64),
            Field::new("bid_0_lots".into(), DataType::Int64),
            Field::new("bid_1_lots".into(), DataType::Int64),
            Field::new("bid_2_lots".into(), DataType::Int64),
            Field::new("bid_3_lots".into(), DataType::Int64),
            Field::new("bid_4_lots".into(), DataType::Int64),
            Field::new("bid_5_lots".into(), DataType::Int64),
            Field::new("bid_6_lots".into(), DataType::Int64),
            Field::new("bid_7_lots".into(), DataType::Int64),
            Field::new("bid_8_lots".into(), DataType::Int64),
            Field::new("bid_9_lots".into(), DataType::Int64),
            Field::new("bid_10_lots".into(), DataType::Int64),
            Field::new("bid_11_lots".into(), DataType::Int64),
            Field::new("bid_12_lots".into(), DataType::Int64),
            Field::new("bid_13_lots".into(), DataType::Int64),
            Field::new("bid_14_lots".into(), DataType::Int64),
            Field::new("bid_15_lots".into(), DataType::Int64),
            Field::new("bid_16_lots".into(), DataType::Int64),
            Field::new("bid_17_lots".into(), DataType::Int64),
            Field::new("bid_18_lots".into(), DataType::Int64),
            Field::new("bid_19_lots".into(), DataType::Int64),
            Field::new("bid_20_lots".into(), DataType::Int64),
            Field::new("bid_21_lots".into(), DataType::Int64),
            Field::new("bid_22_lots".into(), DataType::Int64),
            Field::new("bid_23_lots".into(), DataType::Int64),
            Field::new("bid_24_lots".into(), DataType::Int64),
            Field::new("bid_25_lots".into(), DataType::Int64),
            Field::new("bid_26_lots".into(), DataType::Int64),
            Field::new("bid_27_lots".into(), DataType::Int64),
            Field::new("bid_28_lots".into(), DataType::Int64),
            Field::new("bid_29_lots".into(), DataType::Int64),
            Field::new("bid_30_lots".into(), DataType::Int64),
            Field::new("bid_31_lots".into(), DataType::Int64),
            Field::new("bid_32_lots".into(), DataType::Int64),
            Field::new("bid_33_lots".into(), DataType::Int64),
            Field::new("bid_34_lots".into(), DataType::Int64),
            Field::new("bid_35_lots".into(), DataType::Int64),
            Field::new("bid_36_lots".into(), DataType::Int64),
            Field::new("bid_37_lots".into(), DataType::Int64),
            Field::new("bid_38_lots".into(), DataType::Int64),
            Field::new("bid_39_lots".into(), DataType::Int64),
            Field::new("bid_40_lots".into(), DataType::Int64),
            Field::new("bid_41_lots".into(), DataType::Int64),
            Field::new("bid_42_lots".into(), DataType::Int64),
            Field::new("bid_43_lots".into(), DataType::Int64),
            Field::new("bid_44_lots".into(), DataType::Int64),
            Field::new("bid_45_lots".into(), DataType::Int64),
            Field::new("bid_46_lots".into(), DataType::Int64),
            Field::new("bid_47_lots".into(), DataType::Int64),
            Field::new("bid_48_lots".into(), DataType::Int64),
            Field::new("bid_49_lots".into(), DataType::Int64),
            Field::new("bid_0_value".into(), DataType::Float64),
            Field::new("bid_1_value".into(), DataType::Float64),
            Field::new("bid_2_value".into(), DataType::Float64),
            Field::new("bid_3_value".into(), DataType::Float64),
            Field::new("bid_4_value".into(), DataType::Float64),
            Field::new("bid_5_value".into(), DataType::Float64),
            Field::new("bid_6_value".into(), DataType::Float64),
            Field::new("bid_7_value".into(), DataType::Float64),
            Field::new("bid_8_value".into(), DataType::Float64),
            Field::new("bid_9_value".into(), DataType::Float64),
            Field::new("bid_10_value".into(), DataType::Float64),
            Field::new("bid_11_value".into(), DataType::Float64),
            Field::new("bid_12_value".into(), DataType::Float64),
            Field::new("bid_13_value".into(), DataType::Float64),
            Field::new("bid_14_value".into(), DataType::Float64),
            Field::new("bid_15_value".into(), DataType::Float64),
            Field::new("bid_16_value".into(), DataType::Float64),
            Field::new("bid_17_value".into(), DataType::Float64),
            Field::new("bid_18_value".into(), DataType::Float64),
            Field::new("bid_19_value".into(), DataType::Float64),
            Field::new("bid_20_value".into(), DataType::Float64),
            Field::new("bid_21_value".into(), DataType::Float64),
            Field::new("bid_22_value".into(), DataType::Float64),
            Field::new("bid_23_value".into(), DataType::Float64),
            Field::new("bid_24_value".into(), DataType::Float64),
            Field::new("bid_25_value".into(), DataType::Float64),
            Field::new("bid_26_value".into(), DataType::Float64),
            Field::new("bid_27_value".into(), DataType::Float64),
            Field::new("bid_28_value".into(), DataType::Float64),
            Field::new("bid_29_value".into(), DataType::Float64),
            Field::new("bid_30_value".into(), DataType::Float64),
            Field::new("bid_31_value".into(), DataType::Float64),
            Field::new("bid_32_value".into(), DataType::Float64),
            Field::new("bid_33_value".into(), DataType::Float64),
            Field::new("bid_34_value".into(), DataType::Float64),
            Field::new("bid_35_value".into(), DataType::Float64),
            Field::new("bid_36_value".into(), DataType::Float64),
            Field::new("bid_37_value".into(), DataType::Float64),
            Field::new("bid_38_value".into(), DataType::Float64),
            Field::new("bid_39_value".into(), DataType::Float64),
            Field::new("bid_40_value".into(), DataType::Float64),
            Field::new("bid_41_value".into(), DataType::Float64),
            Field::new("bid_42_value".into(), DataType::Float64),
            Field::new("bid_43_value".into(), DataType::Float64),
            Field::new("bid_44_value".into(), DataType::Float64),
            Field::new("bid_45_value".into(), DataType::Float64),
            Field::new("bid_46_value".into(), DataType::Float64),
            Field::new("bid_47_value".into(), DataType::Float64),
            Field::new("bid_48_value".into(), DataType::Float64),
            Field::new("bid_49_value".into(), DataType::Float64),
            Field::new("ask_0_price".into(), DataType::Float64),
            Field::new("ask_1_price".into(), DataType::Float64),
            Field::new("ask_2_price".into(), DataType::Float64),
            Field::new("ask_3_price".into(), DataType::Float64),
            Field::new("ask_4_price".into(), DataType::Float64),
            Field::new("ask_5_price".into(), DataType::Float64),
            Field::new("ask_6_price".into(), DataType::Float64),
            Field::new("ask_7_price".into(), DataType::Float64),
            Field::new("ask_8_price".into(), DataType::Float64),
            Field::new("ask_9_price".into(), DataType::Float64),
            Field::new("ask_10_price".into(), DataType::Float64),
            Field::new("ask_11_price".into(), DataType::Float64),
            Field::new("ask_12_price".into(), DataType::Float64),
            Field::new("ask_13_price".into(), DataType::Float64),
            Field::new("ask_14_price".into(), DataType::Float64),
            Field::new("ask_15_price".into(), DataType::Float64),
            Field::new("ask_16_price".into(), DataType::Float64),
            Field::new("ask_17_price".into(), DataType::Float64),
            Field::new("ask_18_price".into(), DataType::Float64),
            Field::new("ask_19_price".into(), DataType::Float64),
            Field::new("ask_20_price".into(), DataType::Float64),
            Field::new("ask_21_price".into(), DataType::Float64),
            Field::new("ask_22_price".into(), DataType::Float64),
            Field::new("ask_23_price".into(), DataType::Float64),
            Field::new("ask_24_price".into(), DataType::Float64),
            Field::new("ask_25_price".into(), DataType::Float64),
            Field::new("ask_26_price".into(), DataType::Float64),
            Field::new("ask_27_price".into(), DataType::Float64),
            Field::new("ask_28_price".into(), DataType::Float64),
            Field::new("ask_29_price".into(), DataType::Float64),
            Field::new("ask_30_price".into(), DataType::Float64),
            Field::new("ask_31_price".into(), DataType::Float64),
            Field::new("ask_32_price".into(), DataType::Float64),
            Field::new("ask_33_price".into(), DataType::Float64),
            Field::new("ask_34_price".into(), DataType::Float64),
            Field::new("ask_35_price".into(), DataType::Float64),
            Field::new("ask_36_price".into(), DataType::Float64),
            Field::new("ask_37_price".into(), DataType::Float64),
            Field::new("ask_38_price".into(), DataType::Float64),
            Field::new("ask_39_price".into(), DataType::Float64),
            Field::new("ask_40_price".into(), DataType::Float64),
            Field::new("ask_41_price".into(), DataType::Float64),
            Field::new("ask_42_price".into(), DataType::Float64),
            Field::new("ask_43_price".into(), DataType::Float64),
            Field::new("ask_44_price".into(), DataType::Float64),
            Field::new("ask_45_price".into(), DataType::Float64),
            Field::new("ask_46_price".into(), DataType::Float64),
            Field::new("ask_47_price".into(), DataType::Float64),
            Field::new("ask_48_price".into(), DataType::Float64),
            Field::new("ask_49_price".into(), DataType::Float64),
            Field::new("ask_0_lots".into(), DataType::Int64),
            Field::new("ask_1_lots".into(), DataType::Int64),
            Field::new("ask_2_lots".into(), DataType::Int64),
            Field::new("ask_3_lots".into(), DataType::Int64),
            Field::new("ask_4_lots".into(), DataType::Int64),
            Field::new("ask_5_lots".into(), DataType::Int64),
            Field::new("ask_6_lots".into(), DataType::Int64),
            Field::new("ask_7_lots".into(), DataType::Int64),
            Field::new("ask_8_lots".into(), DataType::Int64),
            Field::new("ask_9_lots".into(), DataType::Int64),
            Field::new("ask_10_lots".into(), DataType::Int64),
            Field::new("ask_11_lots".into(), DataType::Int64),
            Field::new("ask_12_lots".into(), DataType::Int64),
            Field::new("ask_13_lots".into(), DataType::Int64),
            Field::new("ask_14_lots".into(), DataType::Int64),
            Field::new("ask_15_lots".into(), DataType::Int64),
            Field::new("ask_16_lots".into(), DataType::Int64),
            Field::new("ask_17_lots".into(), DataType::Int64),
            Field::new("ask_18_lots".into(), DataType::Int64),
            Field::new("ask_19_lots".into(), DataType::Int64),
            Field::new("ask_20_lots".into(), DataType::Int64),
            Field::new("ask_21_lots".into(), DataType::Int64),
            Field::new("ask_22_lots".into(), DataType::Int64),
            Field::new("ask_23_lots".into(), DataType::Int64),
            Field::new("ask_24_lots".into(), DataType::Int64),
            Field::new("ask_25_lots".into(), DataType::Int64),
            Field::new("ask_26_lots".into(), DataType::Int64),
            Field::new("ask_27_lots".into(), DataType::Int64),
            Field::new("ask_28_lots".into(), DataType::Int64),
            Field::new("ask_29_lots".into(), DataType::Int64),
            Field::new("ask_30_lots".into(), DataType::Int64),
            Field::new("ask_31_lots".into(), DataType::Int64),
            Field::new("ask_32_lots".into(), DataType::Int64),
            Field::new("ask_33_lots".into(), DataType::Int64),
            Field::new("ask_34_lots".into(), DataType::Int64),
            Field::new("ask_35_lots".into(), DataType::Int64),
            Field::new("ask_36_lots".into(), DataType::Int64),
            Field::new("ask_37_lots".into(), DataType::Int64),
            Field::new("ask_38_lots".into(), DataType::Int64),
            Field::new("ask_39_lots".into(), DataType::Int64),
            Field::new("ask_40_lots".into(), DataType::Int64),
            Field::new("ask_41_lots".into(), DataType::Int64),
            Field::new("ask_42_lots".into(), DataType::Int64),
            Field::new("ask_43_lots".into(), DataType::Int64),
            Field::new("ask_44_lots".into(), DataType::Int64),
            Field::new("ask_45_lots".into(), DataType::Int64),
            Field::new("ask_46_lots".into(), DataType::Int64),
            Field::new("ask_47_lots".into(), DataType::Int64),
            Field::new("ask_48_lots".into(), DataType::Int64),
            Field::new("ask_49_lots".into(), DataType::Int64),
            Field::new("ask_0_value".into(), DataType::Float64),
            Field::new("ask_1_value".into(), DataType::Float64),
            Field::new("ask_2_value".into(), DataType::Float64),
            Field::new("ask_3_value".into(), DataType::Float64),
            Field::new("ask_4_value".into(), DataType::Float64),
            Field::new("ask_5_value".into(), DataType::Float64),
            Field::new("ask_6_value".into(), DataType::Float64),
            Field::new("ask_7_value".into(), DataType::Float64),
            Field::new("ask_8_value".into(), DataType::Float64),
            Field::new("ask_9_value".into(), DataType::Float64),
            Field::new("ask_10_value".into(), DataType::Float64),
            Field::new("ask_11_value".into(), DataType::Float64),
            Field::new("ask_12_value".into(), DataType::Float64),
            Field::new("ask_13_value".into(), DataType::Float64),
            Field::new("ask_14_value".into(), DataType::Float64),
            Field::new("ask_15_value".into(), DataType::Float64),
            Field::new("ask_16_value".into(), DataType::Float64),
            Field::new("ask_17_value".into(), DataType::Float64),
            Field::new("ask_18_value".into(), DataType::Float64),
            Field::new("ask_19_value".into(), DataType::Float64),
            Field::new("ask_20_value".into(), DataType::Float64),
            Field::new("ask_21_value".into(), DataType::Float64),
            Field::new("ask_22_value".into(), DataType::Float64),
            Field::new("ask_23_value".into(), DataType::Float64),
            Field::new("ask_24_value".into(), DataType::Float64),
            Field::new("ask_25_value".into(), DataType::Float64),
            Field::new("ask_26_value".into(), DataType::Float64),
            Field::new("ask_27_value".into(), DataType::Float64),
            Field::new("ask_28_value".into(), DataType::Float64),
            Field::new("ask_29_value".into(), DataType::Float64),
            Field::new("ask_30_value".into(), DataType::Float64),
            Field::new("ask_31_value".into(), DataType::Float64),
            Field::new("ask_32_value".into(), DataType::Float64),
            Field::new("ask_33_value".into(), DataType::Float64),
            Field::new("ask_34_value".into(), DataType::Float64),
            Field::new("ask_35_value".into(), DataType::Float64),
            Field::new("ask_36_value".into(), DataType::Float64),
            Field::new("ask_37_value".into(), DataType::Float64),
            Field::new("ask_38_value".into(), DataType::Float64),
            Field::new("ask_39_value".into(), DataType::Float64),
            Field::new("ask_40_value".into(), DataType::Float64),
            Field::new("ask_41_value".into(), DataType::Float64),
            Field::new("ask_42_value".into(), DataType::Float64),
            Field::new("ask_43_value".into(), DataType::Float64),
            Field::new("ask_44_value".into(), DataType::Float64),
            Field::new("ask_45_value".into(), DataType::Float64),
            Field::new("ask_46_value".into(), DataType::Float64),
            Field::new("ask_47_value".into(), DataType::Float64),
            Field::new("ask_48_value".into(), DataType::Float64),
            Field::new("ask_49_value".into(), DataType::Float64),
        ])
    }

    pub fn df(&self) -> DataFrame {
        df!(
            "ts_nanos" => [self.ts],
            "bid_0_price" => [self.bid_price(0)],
            "bid_1_price" => [self.bid_price(1)],
            "bid_2_price" => [self.bid_price(2)],
            "bid_3_price" => [self.bid_price(3)],
            "bid_4_price" => [self.bid_price(4)],
            "bid_5_price" => [self.bid_price(5)],
            "bid_6_price" => [self.bid_price(6)],
            "bid_7_price" => [self.bid_price(7)],
            "bid_8_price" => [self.bid_price(8)],
            "bid_9_price" => [self.bid_price(9)],
            "bid_10_price" => [self.bid_price(10)],
            "bid_11_price" => [self.bid_price(11)],
            "bid_12_price" => [self.bid_price(12)],
            "bid_13_price" => [self.bid_price(13)],
            "bid_14_price" => [self.bid_price(14)],
            "bid_15_price" => [self.bid_price(15)],
            "bid_16_price" => [self.bid_price(16)],
            "bid_17_price" => [self.bid_price(17)],
            "bid_18_price" => [self.bid_price(18)],
            "bid_19_price" => [self.bid_price(19)],
            "bid_20_price" => [self.bid_price(20)],
            "bid_21_price" => [self.bid_price(21)],
            "bid_22_price" => [self.bid_price(22)],
            "bid_23_price" => [self.bid_price(23)],
            "bid_24_price" => [self.bid_price(24)],
            "bid_25_price" => [self.bid_price(25)],
            "bid_26_price" => [self.bid_price(26)],
            "bid_27_price" => [self.bid_price(27)],
            "bid_28_price" => [self.bid_price(28)],
            "bid_29_price" => [self.bid_price(29)],
            "bid_30_price" => [self.bid_price(30)],
            "bid_31_price" => [self.bid_price(31)],
            "bid_32_price" => [self.bid_price(32)],
            "bid_33_price" => [self.bid_price(33)],
            "bid_34_price" => [self.bid_price(34)],
            "bid_35_price" => [self.bid_price(35)],
            "bid_36_price" => [self.bid_price(36)],
            "bid_37_price" => [self.bid_price(37)],
            "bid_38_price" => [self.bid_price(38)],
            "bid_39_price" => [self.bid_price(39)],
            "bid_40_price" => [self.bid_price(40)],
            "bid_41_price" => [self.bid_price(41)],
            "bid_42_price" => [self.bid_price(42)],
            "bid_43_price" => [self.bid_price(43)],
            "bid_44_price" => [self.bid_price(44)],
            "bid_45_price" => [self.bid_price(45)],
            "bid_46_price" => [self.bid_price(46)],
            "bid_47_price" => [self.bid_price(47)],
            "bid_48_price" => [self.bid_price(48)],
            "bid_49_price" => [self.bid_price(49)],
            "bid_0_lots" => [self.bid_lots(0)],
            "bid_1_lots" => [self.bid_lots(1)],
            "bid_2_lots" => [self.bid_lots(2)],
            "bid_3_lots" => [self.bid_lots(3)],
            "bid_4_lots" => [self.bid_lots(4)],
            "bid_5_lots" => [self.bid_lots(5)],
            "bid_6_lots" => [self.bid_lots(6)],
            "bid_7_lots" => [self.bid_lots(7)],
            "bid_8_lots" => [self.bid_lots(8)],
            "bid_9_lots" => [self.bid_lots(9)],
            "bid_10_lots" => [self.bid_lots(10)],
            "bid_11_lots" => [self.bid_lots(11)],
            "bid_12_lots" => [self.bid_lots(12)],
            "bid_13_lots" => [self.bid_lots(13)],
            "bid_14_lots" => [self.bid_lots(14)],
            "bid_15_lots" => [self.bid_lots(15)],
            "bid_16_lots" => [self.bid_lots(16)],
            "bid_17_lots" => [self.bid_lots(17)],
            "bid_18_lots" => [self.bid_lots(18)],
            "bid_19_lots" => [self.bid_lots(19)],
            "bid_20_lots" => [self.bid_lots(20)],
            "bid_21_lots" => [self.bid_lots(21)],
            "bid_22_lots" => [self.bid_lots(22)],
            "bid_23_lots" => [self.bid_lots(23)],
            "bid_24_lots" => [self.bid_lots(24)],
            "bid_25_lots" => [self.bid_lots(25)],
            "bid_26_lots" => [self.bid_lots(26)],
            "bid_27_lots" => [self.bid_lots(27)],
            "bid_28_lots" => [self.bid_lots(28)],
            "bid_29_lots" => [self.bid_lots(29)],
            "bid_30_lots" => [self.bid_lots(30)],
            "bid_31_lots" => [self.bid_lots(31)],
            "bid_32_lots" => [self.bid_lots(32)],
            "bid_33_lots" => [self.bid_lots(33)],
            "bid_34_lots" => [self.bid_lots(34)],
            "bid_35_lots" => [self.bid_lots(35)],
            "bid_36_lots" => [self.bid_lots(36)],
            "bid_37_lots" => [self.bid_lots(37)],
            "bid_38_lots" => [self.bid_lots(38)],
            "bid_39_lots" => [self.bid_lots(39)],
            "bid_40_lots" => [self.bid_lots(40)],
            "bid_41_lots" => [self.bid_lots(41)],
            "bid_42_lots" => [self.bid_lots(42)],
            "bid_43_lots" => [self.bid_lots(43)],
            "bid_44_lots" => [self.bid_lots(44)],
            "bid_45_lots" => [self.bid_lots(45)],
            "bid_46_lots" => [self.bid_lots(46)],
            "bid_47_lots" => [self.bid_lots(47)],
            "bid_48_lots" => [self.bid_lots(48)],
            "bid_49_lots" => [self.bid_lots(49)],
            "bid_0_value" => [self.bid_value(0)],
            "bid_1_value" => [self.bid_value(1)],
            "bid_2_value" => [self.bid_value(2)],
            "bid_3_value" => [self.bid_value(3)],
            "bid_4_value" => [self.bid_value(4)],
            "bid_5_value" => [self.bid_value(5)],
            "bid_6_value" => [self.bid_value(6)],
            "bid_7_value" => [self.bid_value(7)],
            "bid_8_value" => [self.bid_value(8)],
            "bid_9_value" => [self.bid_value(9)],
            "bid_10_value" => [self.bid_value(10)],
            "bid_11_value" => [self.bid_value(11)],
            "bid_12_value" => [self.bid_value(12)],
            "bid_13_value" => [self.bid_value(13)],
            "bid_14_value" => [self.bid_value(14)],
            "bid_15_value" => [self.bid_value(15)],
            "bid_16_value" => [self.bid_value(16)],
            "bid_17_value" => [self.bid_value(17)],
            "bid_18_value" => [self.bid_value(18)],
            "bid_19_value" => [self.bid_value(19)],
            "bid_20_value" => [self.bid_value(20)],
            "bid_21_value" => [self.bid_value(21)],
            "bid_22_value" => [self.bid_value(22)],
            "bid_23_value" => [self.bid_value(23)],
            "bid_24_value" => [self.bid_value(24)],
            "bid_25_value" => [self.bid_value(25)],
            "bid_26_value" => [self.bid_value(26)],
            "bid_27_value" => [self.bid_value(27)],
            "bid_28_value" => [self.bid_value(28)],
            "bid_29_value" => [self.bid_value(29)],
            "bid_30_value" => [self.bid_value(30)],
            "bid_31_value" => [self.bid_value(31)],
            "bid_32_value" => [self.bid_value(32)],
            "bid_33_value" => [self.bid_value(33)],
            "bid_34_value" => [self.bid_value(34)],
            "bid_35_value" => [self.bid_value(35)],
            "bid_36_value" => [self.bid_value(36)],
            "bid_37_value" => [self.bid_value(37)],
            "bid_38_value" => [self.bid_value(38)],
            "bid_39_value" => [self.bid_value(39)],
            "bid_40_value" => [self.bid_value(40)],
            "bid_41_value" => [self.bid_value(41)],
            "bid_42_value" => [self.bid_value(42)],
            "bid_43_value" => [self.bid_value(43)],
            "bid_44_value" => [self.bid_value(44)],
            "bid_45_value" => [self.bid_value(45)],
            "bid_46_value" => [self.bid_value(46)],
            "bid_47_value" => [self.bid_value(47)],
            "bid_48_value" => [self.bid_value(48)],
            "bid_49_value" => [self.bid_value(49)],
            "ask_0_price" => [self.ask_price(0)],
            "ask_1_price" => [self.ask_price(1)],
            "ask_2_price" => [self.ask_price(2)],
            "ask_3_price" => [self.ask_price(3)],
            "ask_4_price" => [self.ask_price(4)],
            "ask_5_price" => [self.ask_price(5)],
            "ask_6_price" => [self.ask_price(6)],
            "ask_7_price" => [self.ask_price(7)],
            "ask_8_price" => [self.ask_price(8)],
            "ask_9_price" => [self.ask_price(9)],
            "ask_10_price" => [self.ask_price(10)],
            "ask_11_price" => [self.ask_price(11)],
            "ask_12_price" => [self.ask_price(12)],
            "ask_13_price" => [self.ask_price(13)],
            "ask_14_price" => [self.ask_price(14)],
            "ask_15_price" => [self.ask_price(15)],
            "ask_16_price" => [self.ask_price(16)],
            "ask_17_price" => [self.ask_price(17)],
            "ask_18_price" => [self.ask_price(18)],
            "ask_19_price" => [self.ask_price(19)],
            "ask_20_price" => [self.ask_price(20)],
            "ask_21_price" => [self.ask_price(21)],
            "ask_22_price" => [self.ask_price(22)],
            "ask_23_price" => [self.ask_price(23)],
            "ask_24_price" => [self.ask_price(24)],
            "ask_25_price" => [self.ask_price(25)],
            "ask_26_price" => [self.ask_price(26)],
            "ask_27_price" => [self.ask_price(27)],
            "ask_28_price" => [self.ask_price(28)],
            "ask_29_price" => [self.ask_price(29)],
            "ask_30_price" => [self.ask_price(30)],
            "ask_31_price" => [self.ask_price(31)],
            "ask_32_price" => [self.ask_price(32)],
            "ask_33_price" => [self.ask_price(33)],
            "ask_34_price" => [self.ask_price(34)],
            "ask_35_price" => [self.ask_price(35)],
            "ask_36_price" => [self.ask_price(36)],
            "ask_37_price" => [self.ask_price(37)],
            "ask_38_price" => [self.ask_price(38)],
            "ask_39_price" => [self.ask_price(39)],
            "ask_40_price" => [self.ask_price(40)],
            "ask_41_price" => [self.ask_price(41)],
            "ask_42_price" => [self.ask_price(42)],
            "ask_43_price" => [self.ask_price(43)],
            "ask_44_price" => [self.ask_price(44)],
            "ask_45_price" => [self.ask_price(45)],
            "ask_46_price" => [self.ask_price(46)],
            "ask_47_price" => [self.ask_price(47)],
            "ask_48_price" => [self.ask_price(48)],
            "ask_49_price" => [self.ask_price(49)],
            "ask_0_lots" => [self.ask_lots(0)],
            "ask_1_lots" => [self.ask_lots(1)],
            "ask_2_lots" => [self.ask_lots(2)],
            "ask_3_lots" => [self.ask_lots(3)],
            "ask_4_lots" => [self.ask_lots(4)],
            "ask_5_lots" => [self.ask_lots(5)],
            "ask_6_lots" => [self.ask_lots(6)],
            "ask_7_lots" => [self.ask_lots(7)],
            "ask_8_lots" => [self.ask_lots(8)],
            "ask_9_lots" => [self.ask_lots(9)],
            "ask_10_lots" => [self.ask_lots(10)],
            "ask_11_lots" => [self.ask_lots(11)],
            "ask_12_lots" => [self.ask_lots(12)],
            "ask_13_lots" => [self.ask_lots(13)],
            "ask_14_lots" => [self.ask_lots(14)],
            "ask_15_lots" => [self.ask_lots(15)],
            "ask_16_lots" => [self.ask_lots(16)],
            "ask_17_lots" => [self.ask_lots(17)],
            "ask_18_lots" => [self.ask_lots(18)],
            "ask_19_lots" => [self.ask_lots(19)],
            "ask_20_lots" => [self.ask_lots(20)],
            "ask_21_lots" => [self.ask_lots(21)],
            "ask_22_lots" => [self.ask_lots(22)],
            "ask_23_lots" => [self.ask_lots(23)],
            "ask_24_lots" => [self.ask_lots(24)],
            "ask_25_lots" => [self.ask_lots(25)],
            "ask_26_lots" => [self.ask_lots(26)],
            "ask_27_lots" => [self.ask_lots(27)],
            "ask_28_lots" => [self.ask_lots(28)],
            "ask_29_lots" => [self.ask_lots(29)],
            "ask_30_lots" => [self.ask_lots(30)],
            "ask_31_lots" => [self.ask_lots(31)],
            "ask_32_lots" => [self.ask_lots(32)],
            "ask_33_lots" => [self.ask_lots(33)],
            "ask_34_lots" => [self.ask_lots(34)],
            "ask_35_lots" => [self.ask_lots(35)],
            "ask_36_lots" => [self.ask_lots(36)],
            "ask_37_lots" => [self.ask_lots(37)],
            "ask_38_lots" => [self.ask_lots(38)],
            "ask_39_lots" => [self.ask_lots(39)],
            "ask_40_lots" => [self.ask_lots(40)],
            "ask_41_lots" => [self.ask_lots(41)],
            "ask_42_lots" => [self.ask_lots(42)],
            "ask_43_lots" => [self.ask_lots(43)],
            "ask_44_lots" => [self.ask_lots(44)],
            "ask_45_lots" => [self.ask_lots(45)],
            "ask_46_lots" => [self.ask_lots(46)],
            "ask_47_lots" => [self.ask_lots(47)],
            "ask_48_lots" => [self.ask_lots(48)],
            "ask_49_lots" => [self.ask_lots(49)],
            "ask_0_value" => [self.ask_value(0)],
            "ask_1_value" => [self.ask_value(1)],
            "ask_2_value" => [self.ask_value(2)],
            "ask_3_value" => [self.ask_value(3)],
            "ask_4_value" => [self.ask_value(4)],
            "ask_5_value" => [self.ask_value(5)],
            "ask_6_value" => [self.ask_value(6)],
            "ask_7_value" => [self.ask_value(7)],
            "ask_8_value" => [self.ask_value(8)],
            "ask_9_value" => [self.ask_value(9)],
            "ask_10_value" => [self.ask_value(10)],
            "ask_11_value" => [self.ask_value(11)],
            "ask_12_value" => [self.ask_value(12)],
            "ask_13_value" => [self.ask_value(13)],
            "ask_14_value" => [self.ask_value(14)],
            "ask_15_value" => [self.ask_value(15)],
            "ask_16_value" => [self.ask_value(16)],
            "ask_17_value" => [self.ask_value(17)],
            "ask_18_value" => [self.ask_value(18)],
            "ask_19_value" => [self.ask_value(19)],
            "ask_20_value" => [self.ask_value(20)],
            "ask_21_value" => [self.ask_value(21)],
            "ask_22_value" => [self.ask_value(22)],
            "ask_23_value" => [self.ask_value(23)],
            "ask_24_value" => [self.ask_value(24)],
            "ask_25_value" => [self.ask_value(25)],
            "ask_26_value" => [self.ask_value(26)],
            "ask_27_value" => [self.ask_value(27)],
            "ask_28_value" => [self.ask_value(28)],
            "ask_29_value" => [self.ask_value(29)],
            "ask_30_value" => [self.ask_value(30)],
            "ask_31_value" => [self.ask_value(31)],
            "ask_32_value" => [self.ask_value(32)],
            "ask_33_value" => [self.ask_value(33)],
            "ask_34_value" => [self.ask_value(34)],
            "ask_35_value" => [self.ask_value(35)],
            "ask_36_value" => [self.ask_value(36)],
            "ask_37_value" => [self.ask_value(37)],
            "ask_38_value" => [self.ask_value(38)],
            "ask_39_value" => [self.ask_value(39)],
            "ask_40_value" => [self.ask_value(40)],
            "ask_41_value" => [self.ask_value(41)],
            "ask_42_value" => [self.ask_value(42)],
            "ask_43_value" => [self.ask_value(43)],
            "ask_44_value" => [self.ask_value(44)],
            "ask_45_value" => [self.ask_value(45)],
            "ask_46_value" => [self.ask_value(46)],
            "ask_47_value" => [self.ask_value(47)],
            "ask_48_value" => [self.ask_value(48)],
            "ask_49_value" => [self.ask_value(49)],
        )
        .unwrap()
    }

    pub fn dt(&self) -> DateTime<Utc> {
        DateTime::from_timestamp_nanos(self.ts)
    }
    pub fn dt_local(&self) -> NaiveDateTime {
        let utc = DateTime::from_timestamp_nanos(self.ts);
        let local: DateTime<Local> = DateTime::from(utc);

        local.naive_local()
    }

    pub fn bid(&self, n: usize) -> Option<&Bid> {
        self.bids.get(n)
    }
    pub fn ask(&self, n: usize) -> Option<&Ask> {
        self.asks.get(n)
    }

    pub fn bid_price(&self, n: usize) -> Option<f64> {
        let bid = self.bids.get(n)?;

        Some(bid.price)
    }
    pub fn bid_lots(&self, n: usize) -> Option<i64> {
        let bid = self.bids.get(n)?;

        Some(bid.lots)
    }
    pub fn bid_value(&self, n: usize) -> Option<f64> {
        let bid = self.bids.get(n)?;

        Some(bid.value)
    }

    pub fn ask_price(&self, n: usize) -> Option<f64> {
        let ask = self.asks.get(n)?;

        Some(ask.price)
    }
    pub fn ask_lots(&self, n: usize) -> Option<i64> {
        let ask = self.asks.get(n)?;

        Some(ask.lots)
    }
    pub fn ask_value(&self, n: usize) -> Option<f64> {
        let ask = self.asks.get(n)?;

        Some(ask.value)
    }
}
impl std::fmt::Display for OrderBook {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "OrderBook: {}", self.dt_local())
    }
}
