from typing import ClassVar

class BarDirection:
    Bull: ClassVar[BarDirection]
    Neutral: ClassVar[BarDirection]
    Bear: ClassVar[BarDirection]
    def value(self) -> int: ...

class PriceRange:
    def __init__(self, low: float, high: float) -> None: ...
    def str(self) -> str: ...
    def eq(self, other: PriceRange) -> bool: ...
    def low(self) -> float: ...
    def high(self) -> float: ...
    def contains(self, value: float) -> bool: ...
    def middle(self) -> float: ...
    def width(self) -> float: ...
