class PriceRange:
    def __init__(self, low: float, high: float) -> None: ...
    def __contains__(self, value: float) -> bool: ...
    def __eq__(self, other: object, /) -> bool: ...
    @property
    def low(self) -> float: ...
    @property
    def high(self) -> float: ...
    def contains(self, value: float) -> bool: ...
    def middle(self) -> float: ...
    def width(self) -> float: ...
