[package]
name = "binds"
version.workspace = true
edition.workspace = true

[lib]
name = "_native"
crate-type = ["cdylib"]
doctest = false

[dependencies]
avin_core = { workspace = true }
avin_domain = { workspace = true }
avin_utils = { workspace = true }

chrono = { workspace = true }
pyo3 = { workspace = true }
